##
# .rubocop.yml
AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'

Style/Documentation:
  Enabled: false
